# Site settings
title: Alice's Adventures Book Series
description: Explore the whimsical world of Alice in Wonderland and Through the Looking-Glass.

baseurl: "/alice.test" # IMPORTANT for GitHub Pages Project sites! This is your repository name.

# Where things are built
permalink: /books/:title/ # Creates URLs like /books/alice-in-wonderland/
source: .
destination: _site

# Jekyll Plugins
plugins:
    - jekyll-feed
    - jekyll-sitemap

# Collections (for our books managed by Decap CMS)
collections:
    books:
        output: true # This tells Jekyll to create a separate HTML page for each book entry

# Defaults for collections (makes it easier to manage book details)
defaults:
- scope:
    path: ""
    type: "books" # Apply these defaults to our 'books' collection
  values:
    layout: "book" # Use the 'book' layout (template) for all book pages
